name: publish
on:
  push:
    branches:
      - v2
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest push
        uses: actions/checkout@v2
      
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Setup Caching
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache  
          
      - name: Install Dependencies
        run: pip install mkdocs-extra-sass-plugin "mkdocs-minify-plugin>=0.3" "mkdocs-redirects>=1.0" mike "jinja2==3.0.3"

      - name: Install MkDocs Insiders
        if: github.event.repository.fork == false
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pip install --upgrade git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git@8.1.9-insiders-4.7.1

      - name: Setup Github
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git checkout v2
       
      - name: Deploy release version       
        run: |
          mike deploy --config-file mkdocs-insiders.yml 2.0 v2
          
      - name: Push changes to server
        run: |
          git checkout gh-pages
          git remote set-url --push origin https://actions:$GITHUB_TOKEN@github.com/ExpressLRS/Docs
          git push -f origin gh-pages
